### ISSUE TITLE
makePlanet is not defined

### ISSUE THREAD

**Issue by Android8675** [RabidOwlbear/DM-planet#1]
trying to generate planet macro on 0.0.0.07, getting error. Tried reinstalling, same error.

`Uncaught (in promise) ReferenceError: makePlanet is not defined
    main https://foundry.shodanscore.com/modules/advanced-macros/Macros.js line 176 > Function:11
    anonymous https://foundry.shodanscore.com/modules/advanced-macros/Macros.js line 176 > Function:14
    callScriptMacroFunction https://foundry.shodanscore.com/modules/advanced-macros/Macros.js:179
    renderMacro https://foundry.shodanscore.com/modules/advanced-macros/Macros.js:197
    executeMacro https://foundry.shodanscore.com/modules/advanced-macros/Macros.js:218
    _onClickMacro https://foundry.shodanscore.com/scripts/foundry.js:28059
    jQuery 2
        dispatch
        handle`

Not exactly sure what's causing the issue. the module.json file I think has the wrong paths to scripts, but not 100% certain.

**Comment by RabidOwlbear** [comment]
This problem should be resolved by the most recent update. The makePlanet function was renamed, and a file path error was corrected.
