### ISSUE TITLE
Tweak Request

### ISSUE THREAD

**Issue by Android8675** [RabidOwlbear/DM-planet#2]
Dunno if you can make some quick changes to this code. Let me know.

![image](https://user-images.githubusercontent.com/440945/148100842-5fec5ac0-d7d3-442b-86b7-bb53545b7d0b.png)

Tier 6 worlds don't actually exist, the logic is, if you roll a 6 for the Tier, that's an anomoly. You take the results of the Tier 6, roll again and take the first roll < 6.

So if you roll a 6 for tier, then a 5, it would be Tier 5X and the traits would be a roll from the Tier 5 table, and the Tier X(6) table. The results from the Tier rolls are correct, just the first header needs tweaking.

Also, any chance to add the rotating planet images back?

**Comment by RabidOwlbear** [comment]
This should be fixed in the most recent update. Thanks for spotting that, marking closed.
